# Generated by Django 3.0.3 on 2020-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('open_time', models.TimeField()),
                ('rating', models.IntegerField()),
                ('approve_by', models.CharField(max_length=20)),
                ('approve_date', models.DateField()),
            ],
        ),
    ]
