# Generated by Django 3.0.3 on 2020-02-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
