# Generated by Django 3.0.3 on 2020-02-27 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default=datetime.date),
            preserve_default=False,
        ),
    ]
