# Generated by Django 3.0.3 on 2020-02-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_restaurant_close_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='close_time',
        ),
    ]
