# Generated by Django 3.0.3 on 2020-02-27 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='idrest',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, to='home.Faculty'),
            preserve_default=False,
        ),
    ]
