# Generated by Django 3.0.3 on 2020-02-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant_idrest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='idrest',
            new_name='faculty_id',
        ),
    ]
