# Generated by Django 3.0.3 on 2020-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_restaurant_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='approve_date',
            field=models.DateTimeField(),
        ),
    ]
