# Generated by Django 3.0.3 on 2020-02-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200227_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='approve_date',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_time',
        ),
    ]
