# Generated by Django 3.0.3 on 2020-02-27 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200227_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default='timezone.now'),
            preserve_default=False,
        ),
    ]
