# Generated by Django 3.0.3 on 2020-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200227_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='faculty_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Faculty'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='approve_date',
            field=models.DateField(),
        ),
    ]
