# Generated by Django 3.0.3 on 2020-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200227_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
    ]
