# Generated by Django 3.0.3 on 2020-02-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200227_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='approve_date',
        ),
    ]
