# Generated by Django 3.0.3 on 2020-02-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
