# Generated by Django 3.0.4 on 2020-03-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('rating', models.IntegerField()),
                ('approve_by', models.CharField(max_length=20)),
                ('approve_date', models.DateField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_home.Faculty')),
            ],
        ),
    ]
