# Generated by Django 3.0.3 on 2020-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_home', '0002_auto_20200305_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_vegan', models.BooleanField()),
            ],
        ),
    ]
