# Generated by Django 3.0.4 on 2020-03-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_home', '0004_restaurantfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantFood',
        ),
    ]
